SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE `results` (
  `id` int(11) NOT NULL,
  `CLIENT_IP` varchar(255) DEFAULT NULL,
  `CLIENT_CITY` varchar(255) DEFAULT NULL,
  `CLIENT_REGION` varchar(255) DEFAULT NULL,
  `CLIENT_COUNTRY` varchar(255) DEFAULT NULL,
  `ISP` varchar(255) DEFAULT NULL,
  `CLIENT_LATITUDE` varchar(255) DEFAULT NULL,
  `CLIENT_LONGITUDE` varchar(255) DEFAULT NULL,
  `TEST_DATE` datetime DEFAULT NULL,
  `SERVER_NAME` varchar(255) DEFAULT NULL,
  `DOWNLOAD_KBPS` int(11) DEFAULT NULL,
  `UPLOAD_KBPS` int(11) DEFAULT NULL,
  `LATENCY` int(11) DEFAULT NULL,
  `CLIENT_BROWSER` varchar(255) DEFAULT NULL,
  `CLIENT_OPERATING_SYSTEM` varchar(255) DEFAULT NULL,
  `USER_AGENT` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `results`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `CLIENT_IP` (`CLIENT_IP`,`ISP`,`TEST_DATE`);


ALTER TABLE `results`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;